import { v4 as uuid } from 'uuid'

import { TimelineEvents } from 'src/interfaces/commonInterfaces'

export const events: TimelineEvents[] = [
  {
    id: uuid(),
    start: '09:00',
    end: '09:15',
    timelineEvent: {
      eventType: 'task',
      state: 'expanded',
      eventData: {
        title: 'Call member to complete annual LTSS assessment',
        status: 'completed',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'call',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    start: '09:30',
    end: '10:00',
    timelineEvent: {
      eventType: 'task',
      state: 'expanded',
      eventData: {
        title: 'Call member to complete annual LTSS assessment',
        status: 'completed',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'call',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    start: '10:30',
    end: '11:00',
    isDraggable: false,
    timelineEvent: {
      eventType: 'break',
      eventData: {
        title: `Travel back from Mrs. Goldberg's home`,
        breakType: 'travel',
        description: 'Approx. 25 to 30 min',
        haveLocation: true,
      },
    },
  },
  {
    id: uuid(),
    start: '11:05',
    end: '11:30',
    isDraggable: true,
    timelineEvent: {
      eventType: 'event',
      state: 'expanded',
      eventData: {
        title: 'Project Presentation',
        status: 'completed',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'home',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    start: '11:30',
    end: '11:45',
    isDraggable: true,
    timelineEvent: {
      eventType: 'task',
      state: 'collapsed',
      eventData: {
        title: 'Call member to complete annual LTSS assessment',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'call',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    start: '11:45',
    end: '12:00',
    isDraggable: true,
    timelineEvent: {
      eventType: 'task',
      state: 'collapsed',
      eventData: {
        title: 'Call member',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'call',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    start: '12:00',
    end: '12:30',
    isDraggable: true,
    timelineEvent: {
      eventType: 'event',
      state: 'collapsed',
      eventData: {
        title: 'Review Frailty Pathway',
        status: 'active',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'home',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    start: '12:30',
    end: '13:00',
    isDraggable: false,
    timelineEvent: {
      eventType: 'break',
      eventData: {
        title: `Travel from your place to Mrs. Goldberg's home by`,
        breakType: 'travel',
        description: 'More traffic than normal expected. Approx. 16 min',
      },
    },
  },
  {
    id: uuid(),
    start: '14:00',
    end: '14:30',
    isDraggable: true,
    timelineEvent: {
      eventType: 'task',
      state: 'expanded',
      eventData: {
        title: 'Call member to complete annual LTSS assessment',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'home',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: false,
        priority: 'urgent',
      },
    },
  },
  {
    id: uuid(),
    start: '16:00',
    end: '16:30',
    isDraggable: false,
    timelineEvent: {
      eventType: 'break',
      eventData: {
        title: `Lunch Break`,
        description: ``,
        breakType: 'lunch',
      },
    },
  },
]

export const aiGeneratedEvents = [
  {
    id: uuid(),
    duration: '30',
    isDraggable: true,
    timelineEvent: {
      eventType: 'event',
      state: 'side',
      eventData: {
        title:
          'Review PCA vendor choices and initiate change per member request',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'careService',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: true,
        priority: 'urgent',
      },
    },
  },
  {
    id: uuid(),
    duration: '30',
    isDraggable: true,
    timelineEvent: {
      eventType: 'task',
      state: 'side',
      eventData: {
        title: 'Call member B to complete annual LTSS assessment',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'call',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: true,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    duration: '60',
    isDraggable: true,
    timelineEvent: {
      eventType: 'event',
      state: 'side',
      eventData: {
        title: 'Refer member to PCP',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'careService',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: true,
        priority: '',
      },
    },
  },
  {
    id: uuid(),
    duration: '30',
    isDraggable: true,
    timelineEvent: {
      eventType: 'task',
      state: 'side',
      eventData: {
        title: 'Call member D to complete annual LTSS assessment',
        status: 'upcoming',
        insights: `Discuss updating service plan to address increasing risk over last 3 months, 3 falls, 1 hospitalization despite execution of interventions`,
        activities: 'Simple games, music therapy, nature walks.',
        communication: 'Direct, clear instructions & visual cues.',
        dueDate: '05/31/2024',
        cardIcon: 'call',
        memberInfo: {
          profile: '',
          name: 'Beena Goldberg',
          age: 31,
          gender: 'F',
        },
        aiScheduled: true,
        priority: '',
      },
    },
  },
]
